// Generated by CoffeeScript 1.6.2
var i, navLink, sStepper, sectionCount, sections, _i, _ref;

sStepper = {};

sectionCount = 0;

sections = [];

sStepper.init = function(stepperElement) {
  sections = $(stepperElement + " .stepper-section");
  return sections.each(function(i) {
    sectionCount++;
    $(this).attr("id", "stepper-section-" + (i + 1));
    if (i === 0) {
      return $(this).addClass("active-step");
    } else {
      return $(this).addClass("hidden-step");
    }
  });
};

$("#sStepper .stepper-next").click(function() {
  return sStepper.nextStep();
});

$("#sStepper .stepper-prev").click(function() {
  return sStepper.prevStep();
});

sStepper.currentStep = function() {
  var activeStep, stepID, stepNumber;

  activeStep = $(".active-step");
  if (activeStep.attr("id") !== void 0) {
    stepID = activeStep.attr("id");
    stepNumber = activeStep.attr("id").split("-")[2];
    return parseInt(stepNumber);
  }
};

sStepper.switchTo = function(targetNum) {
  var currentStep, enterCallback, exitCallback, newStep;

  console.log(sectionCount);
  if (targetNum > sectionCount) {
    targetNum = 1;
  } else if (targetNum <= 0) {
    targetNum = sectionCount;
  }
  currentStep = sStepper.currentStep();
  $("#stepper-section-" + currentStep).removeClass("active-step").addClass("hidden-step");
  newStep = $("#stepper-section-" + targetNum);
  newStep.addClass("active-step").removeClass("hidden-step");
  exitCallback = $("#stepper-section-" + currentStep).attr("data-exit-callback");
  enterCallback = $("#stepper-section-" + targetNum).attr("data-enter-callback");
  if (enterCallback !== void 0) {
    eval(enterCallback);
  }
  if (exitCallback !== void 0) {
    return eval(exitCallback);
  }
};

sStepper.nextStep = function() {
  var currentStep;

  currentStep = sStepper.currentStep();
  return sStepper.switchTo(currentStep + 1);
};

sStepper.prevStep = function() {
  var currentStep;

  currentStep = sStepper.currentStep();
  return sStepper.switchTo(currentStep - 1);
};

for (i = _i = 1, _ref = $(".stepper-section").length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
  navLink = $("<a href='#' onclick='sStepper.switchTo(" + i + ")'>Section " + i + " </a> ");
  $("#stepper-navigation").append(navLink);
}
